### ISSUE TITLE
Default position of picture means that buttons can't be clicked.

### ISSUE THREAD

**Issue by Lauriethefish** [FrozenAlex/Nya-quest#7]
When opening the game with this mod for the first time, the image is positioned such that the "nya" button cannot be pressed as it is blocked by the main menu. The "grab" button that you use to move the thing is just about clickable but barely, so you have to be super precise to fix the issue

To fix: Shift the default position up a little bit.

**Comment by FrozenAlex** [comment]
https://github.com/FrozenAlex/Nya-quest/commit/8aace583a4df18453c0666324f87b17febc683f1 This commit fixes the issue. Raised it a bit.
